### ISSUE TITLE
Add cudatoolkit shim to environment.yml

### ISSUE THREAD

**Issue by mikemhenry** [OpenFreeEnergy/kartograf#3]
We can save some time in our CI by adding a channel to our environment.yml that will prevent us from pulling in `cudatoolkit`

**Comment by dwhswenson** [comment]
Won't be necessary once the openfe dependency is removed, right? (looks like that's intended here)

At least, I don't think anything else has a hard dependency on CUDA.

**Comment by mikemhenry** [comment]
Correct. I've also been working on improving conda-forge packages so they don't download the cudatoolkit if there isn't a GPU (which conda uses a virtual package to detect) but all it takes is one package in the dependency tree to not be nice and then you get the cudatoolkit 🙃. 

We should keep an eye on it to make sure it doesn't get pulled in when we remove opener

**Comment by RiesBen** [comment]
removed the openfe dependency :)
