### ISSUE TITLE
filter_atoms_h_only_h_mapped filters even mapped heavy atoms

### ISSUE THREAD

**Issue by okbckim** [OpenFreeEnergy/kartograf#37]
**Describe the bug**

function filter_atoms_h_only_h_mapped filters mapped heavy atoms where they are different elements.

In this condition, only same elements including heavy atoms are mapped. But this function should only filter hydrogen <-> heavy atoms according to function name and doc.

        if (atomA.GetAtomicNum() == atomB.GetAtomicNum() == 1) or (
            atomA.GetAtomicNum() == atomB.GetAtomicNum() != 1
        ):

**Comment by RiesBen** [comment]
Oha! thanks for finding this! I will fix it :)

**Comment by RiesBen** [comment]
@okbckim this should be fixed now :)
