### ISSUE TITLE
problems with pip installation

### ISSUE THREAD

**Issue by David-Araripe** [OpenFreeEnergy/kartograf#40]
First of all, thanks for the nice package!

While trying it out I encountered two problems after installing it with `python -m pip install kartograph`:
1. The package installed didn't have `dill` in the list of dependencies (I see that's fixed now on the pyproject.toml);
2. Installing kartograph via pip also installed an outdated version of gufe (0.4), which didn't have some functions used by this package.

One thing that could be done is to add information on the README file that the packages can also be installed directly from their respective GitHub repos, as in:
```bash
python -m pip install git+https://github.com/OpenFreeEnergy/gufe.git
python -m pip install git+https://github.com/OpenFreeEnergy/kartograf.git
```
The drawback of this approach is that having this listed on the pyproject.toml as an installation strategy prevents the package from being uploaded to PyPI.

Please let me know if that's something you'd like to have, happy to make a PR.

**Comment by IAlibay** [comment]
Thanks for reporting this @David-Araripe.

My 2 cents (hoping that others will weigh in too). Because of `gufe`'s `openff-toolkit` dependency, I'm not sure if it's possible to do a proper pypi release of kartograf. The idea was brought up here: https://github.com/OpenFreeEnergy/gufe/issues/247 but I'm not sure how feasible it is anymore.

**Comment by David-Araripe** [comment]
Thanks for reporting that @IAlibay , I didn't notice that since my environment already had `openff-toolkit` installed. Good to know!

**Comment by RiesBen** [comment]
Hi @David-Araripe ,
Thanks a lot for your suggestions! :) 

From here I take, the following:
- [ ] New pip release - soon
- [ ] Update readme for dev install instructions
- [ ] check why gufe is so old :)

**Comment by RiesBen** [comment]
This is solved.
