### ISSUE TITLE
Filter that disallows hybridization changes

### ISSUE THREAD

**Issue by hannahbaumann** [OpenFreeEnergy/kartograf#41]
In some mappings in ligands in the PLB system, mapping atoms that are connected by single or double bonds can lead to problems. It would be great to see if mappings that do not map these hybridization changes would perform better.

Example 1: P38 Edge lig_p38a_2gg - lig_p38a_2ee
![download](https://github.com/OpenFreeEnergy/kartograf/assets/43765638/943157e3-c58b-4abd-8d0e-e570293c2025)

Mapping of sulfone and amide let to "stereo inversion" with OpenMM 8.0.0
![Screen Shot 2024-04-10 at 2 15 21 PM](https://github.com/OpenFreeEnergy/kartograf/assets/43765638/a6f4443c-fd4c-4014-9a37-650c1d3a282c)

Other example:
CDK8 Lig_25 - lig_24

![download-1](https://github.com/OpenFreeEnergy/kartograf/assets/43765638/a81765bd-4a39-449e-b7e3-8e90b1bb3428)

**Comment by RiesBen** [comment]
Hi @hannahbaumann ,
do you think this filter could help you out?
https://github.com/OpenFreeEnergy/kartograf/blob/8ef8f8850ed1bbf0afcf656bc80172bd305f5f91/src/kartograf/filters/element_change.py#L54

**Comment by RiesBen** [comment]
I think this is solved.
