### ISSUE TITLE
fused ring atom mapping/scoring for single/hybrid topology methods

### ISSUE THREAD

**Issue by JenkeScheen** [OpenFreeEnergy/kartograf#44]
we've run into a few problematic mappings with the `kartograf` mapper for fused ring systems. `kartograf` maps the following example (red are atoms mapped to remove):
![image](https://github.com/OpenFreeEnergy/kartograf/assets/43140137/9147db57-aadb-4286-8d34-bb101a4aac15)

But with single/hybrid topology methods this won't work. Instead, we would want a mapping like this:
![image](https://github.com/OpenFreeEnergy/kartograf/assets/43140137/bb54d5eb-3408-4a09-80e3-8c5e81921035)
which is of course not very efficient but with enough sampling is _much_ more likely to give an accurate DDG estimate. If you want to reproduce our particular transformation you can use SMILES `c1ccc(cc1)COC(=O)Nc2cc(cc(c2)Cl)C(=O)Nc3ccc4c(c3)CC[C@@H]4N` and `c1ccc(cc1)COC(=O)Nc2cc(cc(c2)Cl)C(=O)Nc3cccc(c3)[C@H]4CCNC4`. 

There are some implementations on `allow ring breaking` options for popular mappers, see [here](https://github.com/OpenBioSim/biosimspace/blob/devel/python/BioSimSpace/Align/_align.py#L769-L772) and [here](https://github.com/OpenFreeEnergy/Lomap/blob/main/lomap/mcs.py#L608) for some examples. Would it be in scope for `kartograf` to have this option too? Currently we need to revert back to `perses` mappers/scorers for this kind of transformation.

**Comment by IAlibay** [comment]
@JenkeScheen can you confirm what version of Kartograf you are using?

**Comment by JenkeScheen** [comment]
I've got `kartograf  1.0.0    pyhd8ed1ab_3  conda-forge`

**Comment by IAlibay** [comment]
Cheers @JenkeScheen, thanks for the report. We'll have a quick stab at this a bit later today / over the next few days - there are filters in place for preventing ring breaking (and one for not doing ring hybridization changes), will need to check why it's not working.

**Comment by David-Araripe** [comment]
Hi @JenkeScheen I happened to work on something similar and I did some processing on kartograf's output to obtain the following:
<p align="center">
<img width="600" src="https://github.com/user-attachments/assets/481e45da-ad8a-403e-8f4e-eec6edfa96e4">
</p>
This was for a work that is yet unpublished but if you're still working on this let me know, happy to share some code
