### ISSUE TITLE
Release v1.1.0

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/kartograf#72]
A new release of Kartograf.

Please note that there has been a v1.1.0 tag but no associated release. Given that this tag is "just there", we should just overwrite it with the current state of things and release a v1.1.0.

TODO:

- [x] Add rever #63 
- [x] Review various deployment needs / issues (see other milestone entries)
- [x] Make a release

**Comment by jameseastwood** [comment]
Meeting scheduled on Dec 17, 12pm EST.
